# Interactive Graph
---
title: "Interactive Graph"
format: html
resources:
  - daily_arrest_data.json
---

The interactive visualization is designed to provide users with a deeper understanding of temporal patterns in NYC arrest trends, focusing on borough-level. By integrating the ability to filter boroughs and adjust the date range, users can explore how arrest counts vary across time and space, revealing meaningful patterns such as weekday peaks, borough-specific trends, and comparisons among boroughs.

<style>
  * {
    font-family: sans-serif;
  }
  #tooltip {
    position: absolute;
    text-align: left;
    padding: 8px;
    font-size: 12px;
    background: white;
    border: 1px solid #ccc;
    border-radius: 4px;
    pointer-events: none;
    display: none;
  }

  #buttons-container {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }

  .borough-button {
    display: flex;
    align-items: center;
    border: 1px solid black;
    padding: 5px;
    margin: 2px;
    cursor: pointer;
    border-radius: 5px;
  }

  .borough-button.active {
    background-color: lightgray;
  }
  .borough-box {
    width: 15px;
    height: 15px;
    margin-right: 5px;
    border: 1px solid black;
  }
  
  .line {
    fill: none;
    stroke-width: 2px;
  }

   #slider-container {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 20px;
  }

  #date-slider {
    width: 80%;
  }
</style>

<div id="plot"></div>
<div id="tooltip"></div>
<div id="buttons-container"></div>
<div id="slider-container"></div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="https://cdn.jsdelivr.net/npm/d3-simple-slider"></script>
<script src="scripts/myscript.js"></script>

Instructions:

1. Selecting/Deselecting Boroughs: Use the clickable buttons below the graph to select or deselect specific boroughs. By toggling these options, the time series plot dynamically updates to show data for only the selected boroughs, making it easier to focus on specific areas of interest.
2. Adjusting the Date Range: Drag the slider beneath the graph to filter the time series data within a specific date range. This feature enables users to zoom into particular time periods, such as a single month or a few weeks, to identify short-term trends and patterns.
3. Exploring Data Points: Hover over any point in the graph to view the exact arrest count for that borough on a specific day. This provides precise details for temporal and spatial comparisons.